## Introduction to Numpy

[Numpy  Package URL](https://www.numpy.org/)

In [1]:
# !pip install numpy

import numpy as np

np.__version__

'1.19.5'

In [ ]:
# one dimensional array
A = np.array([1,2,3,4,5,6])

print('Shape:' , A.shape)
A

Shape: (6,)


array([1, 2, 3, 4, 5, 6])

In [3]:
# two dimensional array
A = np.array([[1, 2, 3], 
              [4, 5, 6]])
# [[1 2 3]
# [4 5 6]]

print(15 * '-')
print('Shape:' , A.shape)
A

---------------
Shape: (2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# We can define the type of the inputs
Af = np.array([1, 2., 3], float)
print(Af)

print(20 * '-')
print('Shape:' , Af.shape)
# n-dimensional array
print('Type: ', type(Af))

[1. 2. 3.]
--------------------
Shape: (3,)
Type:  <class 'numpy.ndarray'>


In [6]:
# same as python's range() function but can step with decimal steps.
A = np.arange(0, 1, 0.2)
print(A)

[0.  0.2 0.4 0.6 0.8]


In [7]:
np.pi

3.141592653589793

In [8]:
# Returns evenly spaced numbers over a specified interval.
A = np.linspace(0, 2*np.pi, 4)
A

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [12]:
A = np.linspace(0, 10, 10)
print(A)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [23]:
# Create random numpy array of shape (5,3)
A = np.random.random((5,3))
print(A)

[[0.5215907  0.9249028  0.66798423]
 [0.67780004 0.60044978 0.05023753]
 [0.71281487 0.91767859 0.3944373 ]
 [0.20232673 0.8327077  0.96008096]
 [0.43424615 0.64387152 0.22172049]]


In [24]:
# Create an array of shape (5,2) by sampling from a Normal distribution 
# of location (center) 0.0 and scale=2.0
a = np.random.normal(loc=0.0,
                     scale=2.0,
                     size=(5,2))
print(a)

[[-1.52738365 -0.54268514]
 [-1.05007841 -3.04009369]
 [ 0.07351983 -0.50464423]
 [ 3.09386103  1.07657311]
 [ 2.69901392  1.29913759]]


In [25]:
# Create an array of shape (5, 3) by sampling from a Normal distribution of location=0.0 and scale=1.0
a = np.random.normal(loc=0.0,
                     scale=1.0,
                     size=(5,3))
print(a)

[[-0.50803123 -0.16077172 -0.46973802]
 [ 0.42721044 -1.12690526 -0.78315102]
 [ 2.191628    1.63744074 -0.01866074]
 [-1.24826192 -0.20888874  0.47331637]
 [ 1.0945046  -1.51147666 -0.17816934]]


In [27]:
a.shape

(5, 3)

In [28]:
# Saving a numpy array as a txt file
np.savetxt("a_out.txt", a)

In [29]:
# Saving a numpy array as a .csv file
a.tofile('foo.csv',
         sep=',',
         format='%10.5f')

In [ ]:
# Second way to save an array as a .csv file.
np.savetxt("foo.csv", a, delimiter=",")

In [30]:
b = np.loadtxt("a_out.txt")
print(b, end='\n\n')
print(type(b))

[[-0.50803123 -0.16077172 -0.46973802]
 [ 0.42721044 -1.12690526 -0.78315102]
 [ 2.191628    1.63744074 -0.01866074]
 [-1.24826192 -0.20888874  0.47331637]
 [ 1.0945046  -1.51147666 -0.17816934]]

<class 'numpy.ndarray'>


In [31]:
b = np.loadtxt("foo.csv", delimiter=',')
print(b)
print(type(b))

[-0.50803 -0.16077 -0.46974  0.42721 -1.12691 -0.78315  2.19163  1.63744
 -0.01866 -1.24826 -0.20889  0.47332  1.0945  -1.51148 -0.17817]
<class 'numpy.ndarray'>


In [33]:
A = np.eye(4, k=0, dtype=float)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
A = np.eye(4, k=1, dtype=float)
print(A)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [35]:
A = np.eye(4, k=-1, dtype=float)
print(A)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [36]:
A = np.zeros([4, 4, 4])
print(A)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [37]:
A = np.ones([4,4], dtype=int)
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [40]:
A = np.diag(range(4))
print(A)

[[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [41]:
A = np.empty((4, 4))
print(A)

[[5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324]]


In [43]:
u = [1, 2, 3, 1]

v = [1, 1, 1, 2]

# unique elements of an array (as an array)
print('Unique elements of the arays')
print(np.unique(u))
print(type(np.unique(v)))

Unique elements of the arays
[1 2 3]
<class 'numpy.ndarray'>


In [44]:
# inner product of 2 arrays

print('Inner product of 2 arrays')
print(np.inner(u, v), end='\n\n')

Inner product of 2 arrays
8



In [ ]:
# outer product of 2 arrays
# https://en.wikipedia.org/wiki/Outer_product
print('Outer product of 2 arrays')
print(np.outer(u, v), end='\n\n')

Outer product of 2 arrays
[[1 1 1 2]
 [2 2 2 4]
 [3 3 3 6]
 [1 1 1 2]]



In [ ]:
# Dot Product of 2 arrays
print('Dot product of 2 arrays')
print(np.dot(u, v), end='\n\n')

Dot product of 2 arrays
8



In [ ]:
# see https://www.tutorialspoint.com/numpy/numpy_tutorial.pdf

In [45]:
# Numpy's basic operations

a = np.array([1, 2, 3], float)
b = np.array([5, 2, 6], float)
print(a)
print(b)

[1. 2. 3.]
[5. 2. 6.]


In [46]:
print('Sum')
print(a + b)  # sum

Sum
[6. 4. 9.]


In [47]:
print('Subtraction')
print(a - b) # element wise subtraction 

Subtraction
[-4.  0. -3.]


In [48]:
print('Multiplication')
print(a * b) # element wise multiplication

Multiplication
[ 5.  4. 18.]


In [49]:
print('Division')
print(b / a) # element wise division

Division
[5. 1. 2.]


In [50]:
print('Modulo')
print(a % b) # element wise modulo 

Modulo
[1. 0. 3.]


In [51]:
print('Power')
print(b ** a)

Power
[  5.   4. 216.]


In [52]:
a = np.array([1.1, 2.7, 3.5], float)
a

array([1.1, 2.7, 3.5])

In [53]:
# floor for each number
print(np.floor(a))

[1. 2. 3.]


In [ ]:
# ceiling for each number
print(np.ceil(a))

[2. 3. 4.]


In [ ]:
# Round elements of the array to the nearest integer.
print(np.rint(a))

[1. 3. 4.]


In [54]:
a

array([1.1, 2.7, 3.5])

In [55]:
# sum of all elements of the array. Same as: np.sum(a)
print(a.sum())

7.300000000000001


In [56]:
# Return the product of array elements over a given axis. Same as: np.prod(a)
print(a.prod())

10.395000000000003


In [57]:
# Average of all elements of the array. Same as: np.mean(a)
print(a.mean())

2.4333333333333336


In [58]:
# Variance of all elements of the array. Same as: np.var(a)
print(a.var())

0.9955555555555554


In [59]:
# Standard Deviation of all elements of the array. Same as: np.std(a)
print(a.std())

0.9977753031397176


In [60]:
# Min element of all elements of the array. Same as: np.min(a)
print(a.min())

1.1


In [61]:
# Max element of all elements of the array. Same as: np.max(a)
print(a.max())

3.5


In [62]:
print(a)
# Given an interval, values outside the interval are clipped to the interval edges
print(a.clip(2.5, 3)) # for more info, check here: https://www.geeksforgeeks.org/numpy-clip-in-python/

[1.1 2.7 3.5]
[2.5 2.7 3. ]


In [63]:
a = np.array([[1,2, 3],
              [3,-1, 3],
              [3,-4, 11]], float)

b = np.array([[2, 4, 4], 
              [1, 3, 3],
              [3,-2, 2]], float)

In [64]:
print('Two numpy arrays: ', end='\n\n')
print(a)

print()

print(b)

Two numpy arrays: 

[[ 1.  2.  3.]
 [ 3. -1.  3.]
 [ 3. -4. 11.]]

[[ 2.  4.  4.]
 [ 1.  3.  3.]
 [ 3. -2.  2.]]


In [65]:
print('Element wise Multiplication')
print(a * b)

Element wise Multiplication
[[ 2.  8. 12.]
 [ 3. -3.  9.]
 [ 9.  8. 22.]]


In [72]:
print(a)
print('Slicing Array A')
print(a[1:2, :])  # 1:2 slices the rows. The ":" means "give me every value"

[[ 1.  2.  3.]
 [ 3. -1.  3.]
 [ 3. -4. 11.]]
Slicing Array A
[[ 3. -1.  3.]]


In [73]:
print('Dot Product of two nd-arrays:')
print(np.dot(a, b))

Dot Product of two nd-arrays:
[[ 13.   4.  16.]
 [ 14.   3.  15.]
 [ 35. -22.  22.]]


In [74]:
print('Maximum values of the dot product of the 2 nd-arrays for each column (for all rows)')
print(np.max(np.dot(a, b) , 0))

Maximum values of the dot product of the 2 nd-arrays for each column (for all rows)
[35.  4. 22.]


In [75]:
print('Maximum values of the dot product of the 2 nd-arrays for each row (for all columns)')
print(np.max(np.dot(a, b) , 1))

Maximum values of the dot product of the 2 nd-arrays for each row (for all columns)
[16. 15. 35.]


In [76]:
print('Maximum values of the dot product of the 2 nd-arrays in respect to the last dimension')
print(np.max(np.dot(a, b) , -1))

Maximum values of the dot product of the 2 nd-arrays in respect to the last dimension
[16. 15. 35.]


In [78]:
a = np.array([[1, 2, 3],
              [3,-1, 3],
              [3,-4, 11]], float)

b = np.array([[2, 4, 4], 
              [1, 3, 3],
              [3,-2, 2]], float)

# Stacking arrays (concatenating)

# Vertical stacking
stacked_v = np.vstack([a,b])

# Horizontal stacking
stacked_h = np.hstack([a,b])

In [79]:
print(stacked_v, end='\n\n')
print(stacked_v.shape)

[[ 1.  2.  3.]
 [ 3. -1.  3.]
 [ 3. -4. 11.]
 [ 2.  4.  4.]
 [ 1.  3.  3.]
 [ 3. -2.  2.]]

(6, 3)


In [ ]:
print(stacked_h, end='\n\n')
print(stacked_h.shape)

[[ 1.  2.  3.  2.  4.  4.]
 [ 3. -1.  3.  1.  3.  3.]
 [ 3. -4. 11.  3. -2.  2.]]

(3, 6)


In [80]:
stacked_v

array([[ 1.,  2.,  3.],
       [ 3., -1.,  3.],
       [ 3., -4., 11.],
       [ 2.,  4.,  4.],
       [ 1.,  3.,  3.],
       [ 3., -2.,  2.]])

In [81]:
# Reshaping arrays (the product of the dimensions must always match (before and after reshaping))
a = stacked_v.reshape(2, 9)

print(stacked_v, end='\n\n')

print(a, end='\n\n')

print(a.shape)

[[ 1.  2.  3.]
 [ 3. -1.  3.]
 [ 3. -4. 11.]
 [ 2.  4.  4.]
 [ 1.  3.  3.]
 [ 3. -2.  2.]]

[[ 1.  2.  3.  3. -1.  3.  3. -4. 11.]
 [ 2.  4.  4.  1.  3.  3.  3. -2.  2.]]

(2, 9)


In [83]:
b = stacked_v.reshape(1, 18)

print(stacked_v, end='\n\n')

print(b, end='\n\n')
print(b.shape)

[[ 1.  2.  3.]
 [ 3. -1.  3.]
 [ 3. -4. 11.]
 [ 2.  4.  4.]
 [ 1.  3.  3.]
 [ 3. -2.  2.]]

[[ 1.  2.  3.  3. -1.  3.  3. -4. 11.  2.  4.  4.  1.  3.  3.  3. -2.  2.]]

(1, 18)


In [84]:
c = stacked_v.reshape(18, 1)

print(stacked_v, end='\n\n')

print(c, end='\n\n')

print(c.shape)

[[ 1.  2.  3.]
 [ 3. -1.  3.]
 [ 3. -4. 11.]
 [ 2.  4.  4.]
 [ 1.  3.  3.]
 [ 3. -2.  2.]]

[[ 1.]
 [ 2.]
 [ 3.]
 [ 3.]
 [-1.]
 [ 3.]
 [ 3.]
 [-4.]
 [11.]
 [ 2.]
 [ 4.]
 [ 4.]
 [ 1.]
 [ 3.]
 [ 3.]
 [ 3.]
 [-2.]
 [ 2.]]

(18, 1)


In [85]:
d = stacked_v.reshape(1, -1)

print(stacked_v, end='\n\n')

print(d, end='\n\n')
print(d.shape)

[[ 1.  2.  3.]
 [ 3. -1.  3.]
 [ 3. -4. 11.]
 [ 2.  4.  4.]
 [ 1.  3.  3.]
 [ 3. -2.  2.]]

[[ 1.  2.  3.  3. -1.  3.  3. -4. 11.  2.  4.  4.  1.  3.  3.  3. -2.  2.]]

(1, 18)


In [87]:
e = stacked_v.reshape(-1, 1)

print(e, end='\n\n')
print(e.shape)

[[ 1.]
 [ 2.]
 [ 3.]
 [ 3.]
 [-1.]
 [ 3.]
 [ 3.]
 [-4.]
 [11.]
 [ 2.]
 [ 4.]
 [ 4.]
 [ 1.]
 [ 3.]
 [ 3.]
 [ 3.]
 [-2.]
 [ 2.]]

(18, 1)


In [88]:
flat_array = np.ndarray.flatten(stacked_v)

flat_array

array([ 1.,  2.,  3.,  3., -1.,  3.,  3., -4., 11.,  2.,  4.,  4.,  1.,
        3.,  3.,  3., -2.,  2.])

In [89]:
# check the difference in shape
flat_array.shape

(18,)

In [ ]:
# More about reshaping in this thread:
# https://stackoverflow.com/questions/22053050/difference-between-numpy-array-shape-r-1-and-r